---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    senderEmail: "{{ senderEmail }}"
  tasks:
    - name: Create IAM Users
      iam_user:
        name: 'cherry'
        state: present
        password: Cherry@cherry1'
    - name: Print Sender's Email ID
      debug:
        msg: "Sender's Email ID: {{ senderEmail }}"
