---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Set random password
      set_fact:
        generated_password: "{{ 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()' | random('password', length=12) }}"
    
    - name: Create IAM Users
      iam_user:
        name: "{{ username }}"
        state: present
        password: "{{ generated_password }}"
