---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: /root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
  tasks:
    - name: Create IAM Users
      iam_user:
        name: 'murali'
        state: present
        password: 'murali'
