---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create IAM Users
      iam_user:
        name: 'cherry'
        state: present
        password: cherry@cherry'
