---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create IAM Users
      iam_user:
        name: 'murali'
        state: present
        password: 'murali'
