---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Generate Password
      community.general.random_password:
        length: 12
        special: yes
        digits: yes
        upperalpha: yes
        loweralpha: yes
      register: generated_password

    - name: Display Generated Password
      debug:
        var: generated_password.password
    
    - name: Create IAM Users
      iam_user:
        name: "{{ username }}"
        state: present
        password: "{{ generated_password.password }}"
