---
- name: Create IAM Users in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #username: "{{ username }}"
  tasks:
    - name: print the values 
      debug:
        msg: "Sender's user name ID: {{ username }}"
    - name: print the values 
      debug:
        msg: "Sender's Email ID: {{ useremail }}"
    - name: Create IAM Users
      iam_user:
        name: "{{ username }}"
        state: present
        password: Cherry@cherry1'
    - name: Print Sender's Email ID
      debug:
        msg: "Sender's Email ID: {{ username }}"
